### ISSUE TITLE
App was removed from play store

### ISSUE THREAD

**Issue by StephenFluin** [FlightOfStairs/ADirStat#1]
Need any help to get it back in?

**Comment by SuperContraptionGuy** [comment]
Definitely would like to see this app get back online, very useful tool.

**Comment by FlightOfStairs** [comment]
Have only just seen this - haven't really looked at the app or the play store listing for years.

I will get it back up, but it will be a couple of weeks before I'm able to do so.

**Comment by FlightOfStairs** [comment]
I've resubmitted on play store with appropriate COPPA declaration. It should be available again soon.

I've been meaning to get to bug-fixes and UI changes for a while - will address those soon.
